from __future__ import annotations
import json, html, pathlib, shutil
from urllib.parse import urljoin
ROOT=pathlib.Path(__file__).resolve().parent
DIST=ROOT/'dist'
SITE=json.loads((ROOT/'site_data.json').read_text(encoding='utf-8'))
PAGES=json.loads((ROOT/'data/pages.json').read_text(encoding='utf-8'))

def esc(s): return html.escape(str(s),quote=True)
def canonical(path='/'): return urljoin(SITE['base_url'].rstrip('/')+'/',path.lstrip('/'))
def nav(): return '<nav><a href="/">ホーム</a><a href="/shindan/">進め方診断</a><a href="/kawagoe-shi/mitsumori-check/">見積チェック</a><a href="/faq/">FAQ</a></nav>'
def ga():
    g=SITE.get('ga4_id','').strip()
    if not g:return ''
    return f'''<script async src="https://www.googletagmanager.com/gtag/js?id={esc(g)}"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){{dataLayer.push(arguments)}}gtag('js',new Date());gtag('config','{esc(g)}');</script>'''
def offer_cta(offer_id='primary',context='content'):
    o=next((x for x in SITE.get('offers',[]) if x.get('id')==offer_id),None)
    if not o or not o.get('url','').strip():return ''
    return f'''<aside class="cta"><span class="pr">PR</span><h2>{esc(o['name'])}</h2><p>依頼条件・対応範囲・料金を確認し、必要に応じて複数社を比較してください。</p><a class="button invert affiliate" data-offer="{esc(offer_id)}" data-context="{esc(context)}" rel="sponsored noopener" target="_blank" href="{esc(o['url'])}">{esc(o.get('label','無料見積もりを確認'))}</a><small>広告・アフィリエイトリンクです。利用者の追加負担はありません。</small></aside>'''
def layout(title,desc,body,path='/',schema=None):
    st=''.join(f'<script type="application/ld+json">{json.dumps(s,ensure_ascii=False)}</script>' for s in ([schema] if isinstance(schema,dict) else (schema or [])))
    return f'''<!doctype html><html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{esc(title)} | {esc(SITE['site_name'])}</title><meta name="description" content="{esc(desc)}"><link rel="canonical" href="{esc(canonical(path))}"><meta name="robots" content="index,follow,max-image-preview:large"><meta property="og:type" content="website"><meta property="og:title" content="{esc(title)} | {esc(SITE['site_name'])}"><meta property="og:description" content="{esc(desc)}"><meta property="og:url" content="{esc(canonical(path))}"><link rel="stylesheet" href="/assets/style.css">{ga()}{st}</head><body><header><div class="wrap header"><a class="brand" href="/">{esc(SITE['site_name'])}</a>{nav()}</div></header><main class="wrap">{body}</main><footer><div class="wrap footer"><div><strong>{esc(SITE['site_name'])}</strong><p>{esc(SITE['tagline'])}</p></div><div><a href="/operator/">運営者情報</a> · <a href="/advertising-policy/">広告ポリシー</a> · <a href="/privacy/">プライバシー</a></div></div></footer><script>document.querySelectorAll('.affiliate').forEach(a=>a.addEventListener('click',()=>{{window.dataLayer=window.dataLayer||[];window.dataLayer.push({{event:'affiliate_click',offer:a.dataset.offer,context:a.dataset.context}})}}));</script></body></html>'''
def write(path,content):
    out=DIST/path
    if out.suffix!='.html':out=out/'index.html'
    out.parent.mkdir(parents=True,exist_ok=True);out.write_text(content,encoding='utf-8')

if DIST.exists():shutil.rmtree(DIST)
(DIST/'assets').mkdir(parents=True)
CSS=r''':root{--ink:#15221c;--sub:#5a6761;--line:#dae5df;--paper:#fbfdfc;--soft:#eef6f1;--accent:#17633f;--accent2:#103d2b;--warn:#fff7df}*{box-sizing:border-box}body{margin:0;color:var(--ink);background:var(--paper);font-family:-apple-system,BlinkMacSystemFont,"Segoe UI","Noto Sans JP",sans-serif;line-height:1.8}a{color:var(--accent)}.wrap{max-width:1080px;margin:auto;padding:0 22px}header{background:#fff;border-bottom:1px solid var(--line);position:sticky;top:0;z-index:10}.header{display:flex;align-items:center;justify-content:space-between;min-height:68px;gap:20px}.brand{font-weight:900;text-decoration:none;color:var(--ink)}nav{display:flex;gap:15px;font-size:14px;flex-wrap:wrap}nav a{text-decoration:none;color:var(--sub)}.hero{padding:64px 0 34px}.eyebrow{font-size:12px;font-weight:800;letter-spacing:.08em;color:var(--accent);text-transform:uppercase}.hero h1{font-size:clamp(31px,5vw,56px);line-height:1.16;letter-spacing:-.035em;margin:.25em 0}.lead{font-size:18px;color:var(--sub);max-width:790px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:15px}.card,.fact{background:#fff;border:1px solid var(--line);border-radius:14px;padding:20px;text-decoration:none;color:var(--ink)}.section{padding:25px 0}.section h2{font-size:27px;line-height:1.4}.notice{background:var(--soft);border-left:4px solid var(--accent);padding:18px 20px;border-radius:8px}.warning{background:var(--warn);border-left:4px solid #d9a515;padding:18px 20px;border-radius:8px}.cta{margin:30px 0;padding:26px;border-radius:14px;background:var(--accent2);color:#fff}.cta .pr{font-size:11px;font-weight:900;border:1px solid currentColor;border-radius:99px;padding:2px 7px}.button{display:inline-block;border:0;cursor:pointer;background:var(--accent);color:#fff;padding:13px 20px;border-radius:9px;font-weight:900;text-decoration:none}.button.invert{background:#fff;color:var(--accent2)}.cta small{display:block;margin-top:8px}.facts{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.diagnosis{display:grid;gap:16px;max-width:780px}.diagnosis label{font-weight:800}.diagnosis select{width:100%;padding:12px;border:1px solid #bac8bf;border-radius:8px;background:#fff}.hint{display:block;font-weight:400;color:var(--sub);font-size:13px}.result{display:none;margin-top:24px;padding:24px;background:#fff;border:2px solid var(--accent);border-radius:12px}.result h2{margin-top:0}.result-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px}.result-box{padding:16px;border-radius:10px;background:var(--soft)}.stop{background:var(--warn)}.public-link{display:inline-block;margin-top:8px}.footer{display:grid;grid-template-columns:2fr 1fr;gap:20px;padding:40px 22px}footer{margin-top:70px;background:#f0f4f1;border-top:1px solid var(--line);font-size:14px}@media(max-width:760px){.header{align-items:flex-start;padding-top:14px;padding-bottom:14px;flex-direction:column}.grid,.facts,.footer,.result-grid{grid-template-columns:1fr}.hero{padding-top:42px}.hero h1{font-size:35px}}'''
(DIST/'assets/style.css').write_text(CSS,encoding='utf-8')

priority=['kawagoe-shi/jikka-katazuke-enkaku','kawagoe-shi/tachiai-fuyo','kawagoe-shi/mitsumori-check','kawagoe-shi/taikyo-kigen','kawagoe-shi/ikkenya-katazuke','kawagoe-shi/ippan-haikibutsu','kawagoe-shi/kichohin-tansaku','kawagoe-shi/shisetsu-nyukyo','kawagoe-shi/kaitori-sousai']
lookup={p['slug']:p for p in PAGES};selected=[lookup[x] for x in priority if x in lookup]
cards=''.join(f'<a class="card" href="/{esc(p["slug"])}/"><small>{esc(p["eyebrow"])}</small><h3>{esc(p["h1"])}</h3><p>{esc(p["description"])}</p></a>' for p in selected)
body=f'''<section class="hero"><div class="eyebrow">Kawagoe / Inherited Home</div><h1>実家を片付ける前に、<br>家の出口を比べる。</h1><p class="lead">相続した実家や空き家は、先に高額な片付けを契約せず、名義・家族の合意・家の出口を確認してから必要な片付けだけ進めます。</p><p><a class="button" href="/shindan/">3分で進め方を整理する</a></p></section><section class="section"><div class="facts"><div class="fact"><strong>1. 名義と家族合意</strong><br>売却や処分を進められる状態か確認</div><div class="fact"><strong>2. 現況で出口確認</strong><br>売却・保有・管理・活用を比較</div><div class="fact"><strong>3. 必要分だけ片付け</strong><br>価値確認後に処分・買取・業者比較へ</div></div></section><section class="section notice"><strong>川越市にも原則無料の空き家相談窓口があります</strong><p>「何から手をつければいいか」から相続、管理、賃貸、売却、解体まで相談できます。</p><p><a href="https://www.city.kawagoe.saitama.jp/kurashi/jyutaku/1003031/1020433.html" target="_blank" rel="noopener">川越市公式の相談窓口を見る</a></p></section>{offer_cta('primary','home')}<section class="section"><h2>片付けが必要になったら確認すること</h2><div class="grid">{cards}</div></section>'''
write('index.html',layout('相続した実家を片付ける前に｜売却・活用・管理・解体を比較','川越市を中心に、相続した実家を片付ける前に名義・家族合意・売却・活用・管理・解体を整理します。',body,'/'))

for p in PAGES:
    secs=''.join(f'<section class="section"><h2>{esc(h)}</h2><ul>'+''.join(f'<li>{esc(x)}</li>' for x in items)+'</ul></section>' for h,items in p['sections'])
    mid=offer_cta('primary',p['slug']) if p['slug'] in priority[:5] else ''
    body=f'''<section class="hero"><div class="eyebrow">{esc(p['eyebrow'])}</div><h1>{esc(p['h1'])}</h1><p class="lead">{esc(p['lead'])}</p></section>{secs}{mid}<section class="section notice"><strong>自治体情報も確認</strong><p>制度・処分方法は川越市の最新公式情報も確認してください。</p></section>'''
    write(p['slug'],layout(p['title'],p['description'],body,'/'+p['slug']+'/'))

shindan='''<section class="hero"><div class="eyebrow">Diagnosis</div><h1>実家の「今やること・まだやらないこと」診断</h1><p class="lead">6つの状況から、片付けや査定を急ぐ前に確認すべき順番を整理します。診断は法律・税務上の個別判断ではありません。</p></section><section class="section"><form id="diag" class="diagnosis"><label>1. 親御さん・実家の状態<select id="status"><option value="alive">親が住んでいる／将来が心配</option><option value="facility">施設入居などで空き家</option><option value="deceased">亡くなり相続が発生</option></select></label><label>2. 名義・相続登記<select id="title"><option value="known">名義・登記状況を確認済み</option><option value="unknown">誰の名義か／登記状況が不明</option><option value="pending">相続手続き中</option></select></label><label>3. 家族・共同相続人の方針<select id="family"><option value="agreed">売る／残す等の方針は合意済み</option><option value="not_agreed">まだ話し合っていない／意見が違う</option><option value="solo">自分だけで判断できる</option></select></label><label>4. 今の希望<select id="exit"><option value="undecided">まだ決めていない</option><option value="sell">売却を検討</option><option value="keep">当面保有・管理したい</option><option value="use">住む／貸すなど活用したい</option></select></label><label>5. 家財・残置物<select id="items"><option value="many">かなり残っている</option><option value="some">一部残っている</option><option value="clear">ほぼ空</option></select><span class="hint">重要書類・形見・価値ある物を確認する前の一括処分は避けます。</span></label><label>6. 距離・期限<select id="distance"><option value="local">現地へ行きやすい</option><option value="far">遠方で何度も行けない</option><option value="urgent">退去・売却など期限が迫っている</option></select></label><button class="button" type="submit">診断結果を見る</button></form><div id="r" class="result" aria-live="polite"><h2 id="result-title"></h2><div class="result-grid"><div class="result-box"><strong>今日やること</strong><p id="do"></p></div><div class="result-box stop"><strong>今はやらないこと</strong><p id="dont"></p></div></div><p id="why"></p><p id="public"></p></div></section><script>
const $=id=>document.getElementById(id);const push=x=>{window.dataLayer=window.dataLayer||[];window.dataLayer.push(x)};
$('diag').addEventListener('submit',e=>{e.preventDefault();let s=$('status').value,t=$('title').value,f=$('family').value,x=$('exit').value,i=$('items').value,d=$('distance').value;let type='undecided',blocked='none',title='まず「決める前の情報」を揃える',todo='川越市の無料相談も使い、名義・家族の意向・維持費・売却/活用の選択肢を1枚に整理する。',dont='片付け・解体・売却を勢いで契約しない。',why='出口が未定の段階では、先に費用をかけると選択肢を狭めることがあります。';
if(t!=='known'){type='inheritance';blocked='title';title='最優先は名義・相続関係の確認';todo='固定資産税資料や登記事項を確認し、誰が手続きを進められるか整理する。';dont='名義が曖昧なまま売却契約や大規模処分を進めない。';why='売却希望があっても、まず権利関係を確認する方が手戻りを減らせます。'}
else if(f==='not_agreed'){type='inheritance';blocked='family_agreement';title='先に家族の方針を揃える';todo='「売る/残す」「誰が管理」「費用負担」「形見・家財」の4点を共同相続人等と確認する。';dont='一人の判断で家財処分や売却を確定しない。';why='家族合意がない状態では、査定額より先に意思決定条件を揃える方が安全です。'}
else if(x==='sell'){type='sale';title='片付け前に現況で売却条件を確認';todo='家財が残る状態での査定可否と、残置物を残す場合/撤去する場合の条件差を確認する。';dont=i==='clear'?'査定前に高額なリフォームや解体を決めない。':'重要書類・形見・価値ある家財を確認せず一括処分しない。';why='片付け費用を先払いする前に、現況価格と必要費用を比較します。'}
else if(x==='keep' || d==='far'){type='manage';title='まず管理空白を止める';todo='郵便、換気、通水、庭木、外観確認の管理頻度を決める。遠方なら川越市の空き家管理連携先も確認する。';dont='管理方法がないまま長期間放置しない。';why='売却を急がない場合でも、管理不全化を防ぐことが先です。'}
else if(x==='use'){type='reuse';title='活用条件と費用を先に比較';todo='住む・貸す場合の修繕費、管理、法的/物理的条件を確認する。';dont='活用可能性を確認せず解体や全処分をしない。';why='活用案ごとの初期費用と継続費を比較してから片付け範囲を決めます。'}
if(s==='deceased'&&t==='known'&&type==='undecided'){type='inheritance';title='相続後の出口を比較する';todo='売却・保有・活用の3案と税務上の期限/要件を専門家・一次情報で確認する。';dont='税制要件を確認せず貸す・壊す・売る判断を確定しない。';why='相続空き家には条件付きの税制措置等があるため、行動順序が重要です。'}
$('result-title').textContent=title;$('do').textContent=todo;$('dont').textContent=dont;$('why').textContent=why;$('public').innerHTML='<a class="public-link" target="_blank" rel="noopener" href="https://www.city.kawagoe.saitama.jp/kurashi/jyutaku/1003031/1020433.html">川越市公式：空き家・空き地の相談窓口</a>'+(type==='manage'?'<br><a class="public-link" target="_blank" rel="noopener" href="https://www.city.kawagoe.saitama.jp/kurashi/jyutaku/1003031/1003044.html">川越市公式：シルバー人材センターとの空き家管理連携</a>':'');$('r').style.display='block';$('r').scrollIntoView({behavior:'smooth',block:'start'});push({event:'diagnosis_complete',diagnosis_result:type,blocked_action:blocked,status:s,title_status:t,family_status:f,exit_intent:x,items:i,distance:d});});
</script>'''
write('shindan',layout('実家片付けの進め方診断','6つの状況から、相続した実家で今やること・まだやらないこと・川越市の相談先を整理します。',shindan,'/shindan/'))

faq='''<section class="hero"><h1>よくある質問</h1></section><section class="section"><h2>片付けてから査定すべき？</h2><p>必ずしも先に全処分する必要はありません。現況で相談できるか確認し、重要書類・形見・価値ある物を確認してから処分範囲を決めます。</p><h2>遠方で管理できません</h2><p>川越市は空き家管理についてシルバー人材センターとの連携を案内しています。売却未定でも管理空白を作らないことが重要です。</p></section>'''
write('faq',layout('よくある質問','実家片付け・相続空き家のよくある質問。',faq,'/faq/'))
for slug,title,text in [('operator','運営者情報',f"運営者：{SITE.get('operator_name','')}"),('advertising-policy','広告ポリシー','当サイトはアフィリエイト広告を掲載する場合があります。広告リンク付近にPR・広告表示を行います。'),('privacy','プライバシーポリシー','アクセス解析を導入する場合があります。個人情報は目的外利用しません。')]:write(slug,layout(title,title,f'<section class="hero"><h1>{esc(title)}</h1></section><section class="section"><p>{esc(text)}</p></section>','/'+slug+'/'))
urls=['/','/shindan/','/faq/','/operator/','/advertising-policy/','/privacy/']+[f'/{p["slug"]}/' for p in PAGES]
(DIST/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+''.join(f'<url><loc>{esc(canonical(u))}</loc></url>' for u in urls)+'</urlset>',encoding='utf-8')
(DIST/'robots.txt').write_text('User-agent: *\nAllow: /\nSitemap: '+canonical('/sitemap.xml')+'\n',encoding='utf-8')
print(f'Built {len(urls)} indexable URLs -> {DIST}')