const grants=[
['川越市','解体補助は個別確認','契約前に市の空き家窓口・対象制度を確認','川越市は解体のメリットだけでなく、解体費用、住宅用地の税軽減が外れる可能性、再建築できない場合があることも案内。先に解体を決めず、建物付き現況査定と解体後の手残りを比較してから判断','https://www.city.kawagoe.saitama.jp/kurashi/jyutaku/1003031/1003041.html'],
['白岡市','受付中・残額少','締切は公式で最新確認','最新の市公式条件を申請前に再確認','https://www.city.shiraoka.lg.jp/soshiki/seikatsukeizaibu/kankyoka/1_1/7523.html'],
['川口市','受付中・対象限定','事前診断 2026-10-30／交付申請 2026-11-13（予算到達で終了）','主対象は、接道がなく建替えできず老朽化した空き家等。接道のある一般的な空き家は補助対象とは限らない。上限額だけで解体を決めず、まず市の事前診断で対象可否を確認し、再建築不可なら土地価値への影響も含めて「建物付き現況売却」と「補助を使った解体後売却」の手残りを比較してから契約','https://www.city.kawaguchi.lg.jp/soshiki/01130/040/akiyatoutaisaku/27633.html'],
['上尾市','受付中','交付申請 2026-10-30（予算到達で早期終了）','対象は原則、概ね1年以上未使用かつ昭和56年5月31日以前に建築された住宅等。築年・空き家期間・予算残を市に確認し、対象外なら補助待ちをせず現況売却との手残り比較へ進む','https://www.city.ageo.lg.jp/page/421263.html'],
['熊谷市','要事前相談','工事着手前に安心安全課へ相談','対象は昭和56年5月31日以前に建築された木造の居住用家屋で、市内にあり1年以上居住されておらず、飛散・落下等で近隣や公道へ影響するおそれがあるなど危険性の要件あり。解体契約を先行せず、市の対象判定と現況売却の手残りを比較してから判断','https://www.city.kumagaya.lg.jp/kurashi/kankyo_sumai/akiyataisaku/jyokyakuhojokin.html'],
['東松山市','受付中','申請 2026-12-28（予算到達で早期終了）','本申請前に市へ事前相談。補助対象可否を確認してから契約・着工判断','https://www.city.higashimatsuyama.lg.jp/soshiki/37/52176.html'],
['富士見市','受付中','除却補助申請 2027-01-31','補助金交付決定後に工事。交付決定前の契約・着工を前提に進めない','https://www.city.fujimi.saitama.jp/kurashi_tetsuzuki/sumai/2018-0511-1113-58/akiyahojoseido.html'],
['深谷市','受付中','事前調査申込 2026-11-30／工事完了 2027-01-29','不良住宅の事前調査を受け、補助金交付決定後に工事を進める','https://www.city.fukaya.saitama.jp/soshiki/kyoudou/jiti/tanto/akiya/akiyahojyo/14716.html'],
['本庄市','受付中（先着順）','令和8年度受付中・予算到達で終了の可能性','申請書類を整える前に市へ事前相談し、補助対象可否を確認してから解体契約を進める','https://www.city.honjo.lg.jp/soshiki/toshiseibi/eizenjutaku/tantoujouhou/akiyataisaku/akiyakaitai/21195.html'],
['鳩山町','受付中（先着順）','2026-04-01受付開始・予算到達で終了','老朽空き家除却は区域により上限50万円または30万円、家財処分も上限10万円。片付け・解体を自費で先行せず、対象可否と予算残を町に確認して現況売却との手残りを比較','https://www.town.hatoyama.saitama.jp/kurashi/sumai_hikkosi/rifomujyokyakuhojyo/page001560.html'],
['ときがわ町','受付中','申請 2026-12-25／完了報告 2027-02-26（予算到達で終了）','対象は1年以上未使用で今後も居住見込みがなく、倒壊等で周辺へ危険を及ぼすおそれのある個人所有の一戸建て等。事前相談票が必要で、交付決定前に工事契約すると補助対象外。町内業者なら上限50万円・その他は上限40万円なので、先に契約せず「補助利用後の解体売却」と「建物付き現況売却」の手残りを比較','https://www.town.tokigawa.lg.jp/Info/3493'],
['坂戸市','受付終了','2026-05-18 上限到達で終了','受付再開を公式で確認するまで補助前提で契約しない','https://www.city.sakado.lg.jp/soshiki/37/28358.html']];
const sel=document.getElementById('grant-city'),out=document.getElementById('grant-result');
if(sel&&out){grants.forEach(g=>{const o=document.createElement('option');o.value=g[0];o.textContent=g[0];sel.appendChild(o)});sel.addEventListener('change',()=>{const g=grants.find(x=>x[0]===sel.value);if(!g){out.innerHTML='';return}const closed=g[1].includes('終了');out.innerHTML=`<h3>${g[0]}：${g[1]}</h3><p><strong>期限：</strong>${g[2]}</p><p><strong>契約判断：</strong>${g[3]}</p><p><strong>${closed?'今やること':'契約前にやること'}：</strong>${closed?'補助前提で進めず、再開有無と別の出口を確認':'自治体へ対象可否・受付状況を確認 → 現況査定 → 見積取得 → 申請/交付決定 → 契約'}</p><p><a class="button" target="_blank" rel="noopener" href="${g[4]}">${g[0]}公式情報を確認</a></p><small>制度は予算・年度で変わります。表示内容は確認時点の情報です。契約・申請前に自治体公式ページで最新の受付状況と要件を再確認してください。</small>`})}